[package]
name = "torrent-inspector"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22.0", features = ["full"] }
axum = { version = "0.5.17", features = ["multipart"] }

serde = { version = "1.0", features = ["derive"] }
serde_bencode = "0.2.3"
serde_bytes = "0.11.7"
